version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: weather-station-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weather
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  rest-api:
    build: ./src/rest-api    # Path to your REST API Dockerfile
    container_name: weather-station-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: weather

volumes:
  mysql-data:
